server:
  port: 18088
  servlet:
    context-path: /shui

spring:
  application:
    name: common_demo
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://host.docker.internal:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: chimanloo1004

      initial-size: 1      # 初始化物理连接个数
      max-active: 20       # 最大连接池数量
      min-idle: 5          # 最小连接池数量
      max-wait: 60000      # 获取连接时最大等待时间(ms)
      pool-prepared-statements: true      # 开启缓存preparedStatement(PSCache)
      max-pool-prepared-statement-per-connection-size: 20      # 启用PSCache后，指定每个连接上PSCache的大小
      validation-query: select 'x'  # 用来检测连接是否有效的sql
      test-on-borrow: false         # 申请连接时不检测连接是否有效
      test-on-return: false         # 归还连接时不检测连接是否有效
      test-while-idle: true         # 申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效（不影响性能）
      time-between-eviction-runs-millis: 60000    # 检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
      min-evictable-idle-time-millis: 300000      # 连接保持空闲而不被驱逐的最小时间(ms)
      filters: stat,wall            # 配置监控统计拦截的filters（不配置则监控界面sql无法统计），监控统计filter:stat，日志filter:log4j，防御sql注入filter:wall
      use-global-data-source-stat: true           # 支持合并多个DruidDataSource的监控数据

      stat-view-servlet:
        enabled: true             # 启用内置的监控页面
        url-pattern: /druid/*     # 内置监控页面的地址
        login-username: admin
        login-password: admin
      aop-patterns: com.shui.controller.*

      web-stat-filter:
        enabled: true                   # 启用StatFilter
        session-stat-enable: true       # 开启session统计功能
        url-pattern: /*                 # 添加过滤规则
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"     #排除一些不必要的url

      filter:
        stat:
          merge-sql: true          # 打开mergeSql(Sql合并)功能
          log-slow-sql: true       # 慢SQL记录(配置超过5秒就是慢，默认是3秒)
          slow-sql-millis: 5000


  # elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          connection-timeout: 120s
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

  # rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: dev
    password: dev
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 1051800045@qq.com
    password: ejychtrurmyibbad

# minio
minio:
  endpoint: http://127.0.0.1:9000
  accesskey: admin
  secretKey: chimanloo1004


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml   # Mapper映射文件
  typeAliasesPackage: com.shui.domain         # Mybatis数据返回类型别名（默认别名为类名）
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: id_worker

logging:
  level:
    com.shui.dao: DEBUG

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /metrics # 访问路径，替代默认的/actuator

# 多数据源
dynamic:
  datasource:
    eblog:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/eblog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: chimanloo1004